_wandb:
    value:
        cli_version: 0.22.3
        e:
            inuymsw4zkvod1kyk4kljgcvsxcqwsxs:
                codePath: ..\wandb_logger.py
                codePathLocal: ..\wandb_logger.py
                cpu_count: 6
                cpu_count_logical: 12
                cudaVersion: "11.1"
                disk:
                    /:
                        total: "342698749952"
                        used: "10857590784"
                email: dhanesh@eligocs.com
                executable: C:\Users\eligo\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\python.exe
                gpu: GeForce GT 710
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Kepler
                      name: GeForce GT 710
                      uuid: GPU-e50926c2-18d6-a065-70f0-0d3813243ccd
                host: EligoCS
                memory:
                    total: "17026105344"
                os: Windows-11-10.0.26100-SP0
                program: D:\LMS Chatbot\pdf-extractor-api\wandb_logger.py
                python: CPython 3.13.9
                root: D:\LMS Chatbot\pdf-extractor-api\public
                startedAt: "2025-11-04T10:41:17.681105Z"
                writerId: inuymsw4zkvod1kyk4kljgcvsxcqwsxs
        m: []
        python_version: 3.13.9
        t:
            "1":
                - 105
            "2":
                - 105
            "3":
                - 2
                - 13
            "4": 3.13.9
            "5": 0.22.3
            "8":
                - 3
            "12": 0.22.3
            "13": windows-amd64
